### ISSUE TITLE
500 error when updating users

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/kaznet-web#334]
this happens because here: https://github.com/onaio/kaznet-web/blob/master/kaznet/apps/users/serializers.py#L335 because the metadata field may have been initialized to None here: https://github.com/onaio/kaznet-web/blob/master/kaznet/apps/users/serializers.py#L333

Here's the stack trace:
```Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/home/user/.local/share/virtualenvs/kaznet-web-Nz89G9xU/lib/python3.6/site-packages/rest_framework/serializers.py", line 208, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/user/work/kaznet-web/kaznet/apps/users/serializers.py", line 335, in update
    instance.metadata["last_password_edit"] = metadata.get(
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by FrankApiyo** [comment]
The solution here will be to wrap this line: https://github.com/onaio/kaznet-web/blob/master/kaznet/apps/users/serializers.py#L335, in a try/except that does nothing when this exception happens
